FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build

WORKDIR /src

COPY AvaloniaApplication1/AvaloniaApplication1.csproj ./AvaloniaApplication1/

RUN dotnet restore ./AvaloniaApplication1/AvaloniaApplication1.csproj

COPY AvaloniaApplication1 ./AvaloniaApplication1

WORKDIR /src/AvaloniaApplication1

RUN dotnet publish \
    AvaloniaApplication1.csproj \
    --configuration Release \
    --runtime linux-x64 \
    --self-contained false \
    --output /publish

FROM mcr.microsoft.com/dotnet/runtime:9.0

WORKDIR /app

COPY --from=build /publish .

ENTRYPOINT ["dotnet", "AvaloniaApplication1.dll"]